language: rust
sudo: required
dist: trusty
rust:
  - nightly
os:
  - linux
addons:
  apt:
    packages:
      - libpulse-dev
      - pulseaudio
      - pulseaudio-utils
      - dbus-x11
services:
  - pulseaudio

before_install:
  - curl -L https://github.com/ferjm/gstreamer-1.14.1-ubuntu-trusty/raw/master/gstreamer_.tar.gz | tar xz
  - mv gstreamer /tmp/
  - export PKG_CONFIG_PATH=/tmp/gstreamer/lib/x86_64-linux-gnu/pkgconfig
  - export GST_PLUGIN_SYSTEM_PATH=$GST_PLUGIN_SYSTEM_PATH:/usr/lib/x86_64-linux-gnu/gstreamer-1.0:/tmp/gstreamer/lib/x86_64-linux-gnu/gstreamer-1.0
  - export GST_PLUGIN_SCANNER=/tmp/gstreamer/libexec/gstreamer-1.0/gst-plugin-scanner
  - export PATH=$PATH:/tmp/gstreamer/bin
  - export LD_LIBRARY_PATH=/tmp/gstreamer/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
  - GST_REGISTRY_FORK=no /tmp/gstreamer/bin/gst-inspect-1.0 audiotestsrc
  - export DISPLAY=:99.0;
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset;

script:
  - cargo build
  - ls examples/*.rs | xargs -I{} basename  {} .rs  | grep -v params_connect | RUST_BACKTRACE=1 GST_DEBUG=3 xargs -I{} cargo ex {}
