[package]
name = "servo-media"
version = "0.1.0"
authors = ["Fernando Jiménez Moreno <ferjmoreno@gmail.com>"]
license = "MPL-2.0"

[lib]
name = "servo_media"

[features]
default = ["gst"]
gst = ["gstreamer"]

[dependencies]
gstreamer = { version = "0.10.2", optional = true }

[build-dependencies]
regex = "0.2.10"
zip = "0.3.1"
