[package]
name = "servo-media"
version = "0.1.0"
authors = ["Fernando Jiménez Moreno <ferjmoreno@gmail.com>"]
license = "MPL-2.0"

[lib]
name = "servo_media"

[features]
default = ["gstreamer"]
gstreamer = []

[dependencies]
