[package]
name = "servo_media"
version = "0.1.0"
authors = ["Fernando Jiménez Moreno <ferjmoreno@gmail.com>"]
license = "MPL-2.0"

[lib]
name = "servo_media"
crate-type = ["cdylib"]
path = "src/lib.rs"

[features]
default = ["gst"]
gst = ["gstreamer", "glib", "gst-plugin", "gstreamer-audio", "gstreamer-base", "byte-slice-cast", "num-traits"]

[dependencies]
byte-slice-cast = { version = "0.1", optional = true }
glib = { version = "0.4", optional = true }
gst-plugin = { version = "0.1", optional = true }
gstreamer = { version = "0.10.2", optional = true }
gstreamer-audio = { version = "0.10", optional = true }
gstreamer-base = { version = "0.10.2", optional = true }
num-traits = { version = "0.1", optional = true }

[build-dependencies]
regex = "0.2.10"
zip = "0.3.1"
