[package]
authors = ["Fernando Jiménez Moreno <ferjmoreno@gmail.com>"]
license = "MPL-2.0"
name = "servo_media"
version = "0.1.0"

[build-dependencies]
regex = "0.2.10"
zip = "0.3.1"

[dependencies]
smallvec = "0.6.1"

[dependencies.petgraph]
version = "0.4.12"
features = ["stable_graph"]

[dependencies.byte-slice-cast]
optional = true
version = "0.1"

[dependencies.gstreamer]
optional = true
version = "0.11"

[dependencies.gstreamer-app]
optional = true
version = "0.11.2"

[dependencies.gstreamer-audio]
optional = true
version = "0.11"

[dependencies.num-traits]
optional = true
version = "0.1"

[features]
default = ["gst"]
gst = ["gstreamer", "gstreamer-audio", "gstreamer-app", "byte-slice-cast", "num-traits"]

[lib]
name = "servo_media"
