[package]
name = "examples"
version = "0.1.0"
license = "MPL-2.0"

[dependencies]
rand = "0.5.0"
servo_media = { path = "../servo-media", features = ["gst"] }

[[bin]]
name = "audio_decoder"
path = "audio_decoder.rs"

[[bin]]
name = "params"
path = "params.rs"

[[bin]]
name = "params_settarget"
path = "params_settarget.rs"

[[bin]]
name = "play"
path = "play.rs"

[[bin]]
name = "play_noise"
path = "play_noise.rs"

[[bin]]
name = "channels"
path = "channels.rs"

[[bin]]
name = "channelsum"
path = "channelsum.rs"
