[package]
name = "servo-media"
version = "0.1.0"
authors = ["Manish Goregaokar <manishsmail@gmail.com>"]

[lib]
name = "servo_media"

[dependencies.servo-media-audio]
path = "../servo-media-audio"


[target.'cfg(not(target_os = "android"))'.dependencies.servo-media-gstreamer]
path = "../servo-media-gstreamer"
